name: CD

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - main

jobs:
  no-op:
    runs-on: ubuntu-latest
    steps:
      - name: Show context
        run: |
          echo "Workflow triggered by ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
